import {sortedFeeds, slug, markdown, xml, link} from './catalog.mjs';

export function renderReadme(catalog) {
  const headings = [...catalog.categories.map(category => category.title), ...catalog.sections.map(section => section.title)];
  const lines = [
    `# ${catalog.title} [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)`,
    '',
    '<!--lint disable awesome-no-ci-badge-->',
    '',
    `[![Lint](https://github.com/${catalog.repository}/actions/workflows/validate.yml/badge.svg?branch=main)](https://github.com/${catalog.repository}/actions/workflows/validate.yml)`,
    '',
    `> ${catalog.description}`,
    '',
    '<!-- Generated from feeds.json. Run npm run build; do not edit this file directly. -->',
    '<!--lint disable awesome-git-repo-age-->',
    '',
    `[Read the news in Sound & State](https://${catalog.repository.split('/')[0]}.github.io/${catalog.repository.split('/')[1]}/) or [download the OPML file](https://raw.githubusercontent.com/${catalog.repository}/main/feeds.opml) for Feedly, NetNewsWire, Inoreader, or another RSS reader. [Suggest a source or correction](CONTRIBUTING.md).`,
    '',
    '## Contents',
    '',
    ...headings.map(title => `- [${title}](#${slug(title)})`),
    '',
  ];
  for (const category of catalog.categories) {
    lines.push(`## ${category.title}`, '', category.description, '');
    for (const feed of sortedFeeds(catalog, category.id)) {
      lines.push(`- [${markdown(feed.name)}](${link(feed.website)}) - ${markdown(feed.description).replace(/\.$/, '')}. [${feed.format}](${feed.feed}).`);
    }
    lines.push('');
  }
  for (const section of catalog.sections) lines.push(`## ${section.title}`, '', ...section.links.map(({name, url}) => `- [${markdown(name)}](${link(url)})`), '');
  return lines.join('\n');
}

export function renderOpml(catalog) {
  const lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<!-- Generated from feeds.json. Run npm run build. -->', '<opml version="2.0">', '  <head>', `    <title>${xml(catalog.title)}</title>`, '  </head>', '  <body>'];
  for (const category of catalog.categories) {
    lines.push(`    <outline text="${xml(category.title)}" title="${xml(category.title)}">`);
    for (const feed of sortedFeeds(catalog, category.id)) {
      // OPML uses type="rss" for both RSS and Atom subscriptions.
      lines.push(`      <outline type="rss" text="${xml(feed.name)}" title="${xml(feed.name)}" description="${xml(feed.description)}" xmlUrl="${xml(feed.feed)}" htmlUrl="${xml(feed.website)}"/>`);
    }
    lines.push('    </outline>');
  }
  lines.push('  </body>', '</opml>', '');
  return lines.join('\n');
}
