import {sortedFeeds, slug, markdown, xml, link} from './catalog.mjs';

export function renderReadme(catalog) {
  const headings = [...catalog.categories.map(category => category.title), ...catalog.sections.map(section => section.title)];
  const lines = [
    `# ${catalog.title} [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)`,
    '',
    `> ${catalog.description}`,
    '',
    '<!-- Generated from feeds.json. Run npm run build; do not edit this file directly. -->',
    '<!-- This independent list is new; the 30-day rule applies to submission to sindresorhus/awesome. -->',
    '<!--lint disable awesome-git-repo-age-->',
    '',
    `[Read the news in Sound & State](https://${catalog.repository.split('/')[0]}.github.io/${catalog.repository.split('/')[1]}/) or [download the OPML file](https://raw.githubusercontent.com/${catalog.repository}/main/feeds.opml) for Feedly, NetNewsWire, Inoreader, or another RSS reader. [Suggest a source or correction](CONTRIBUTING.md).`,
    '',
    `${catalog.feeds.length} curated feeds. Reviewed ${catalog.reviewedOn}. The starting point is a Seattle-focused Feedly export, so coverage elsewhere in Washington is still growing.`,
    '',
    '## Contents',
    '',
    ...headings.map(title => `- [${title}](#${slug(title)})`),
    '',
  ];
  for (const category of catalog.categories) {
    lines.push(`## ${category.title}`, '', category.description, '');
    for (const feed of sortedFeeds(catalog, category.id)) {
      lines.push(`- [${markdown(feed.name)}](${link(feed.website)}) - ${markdown(feed.description).replace(/\.$/, '')}. [${feed.format}](${feed.feed}).`);
    }
    lines.push('');
  }
  for (const section of catalog.sections) lines.push(`## ${section.title}`, '', ...section.paragraphs.flatMap(p => [p, '']));
  return lines.join('\n');
}

export function renderOpml(catalog) {
  const lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<!-- Generated from feeds.json. Run npm run build. -->', '<opml version="2.0">', '  <head>', `    <title>${xml(catalog.title)}</title>`, '  </head>', '  <body>'];
  for (const category of catalog.categories) {
    lines.push(`    <outline text="${xml(category.title)}" title="${xml(category.title)}">`);
    for (const feed of sortedFeeds(catalog, category.id)) {
      // OPML uses type="rss" for both RSS and Atom subscriptions.
      lines.push(`      <outline type="rss" text="${xml(feed.name)}" title="${xml(feed.name)}" description="${xml(feed.description)}" xmlUrl="${xml(feed.feed)}" htmlUrl="${xml(feed.website)}"/>`);
    }
    lines.push('    </outline>');
  }
  lines.push('  </body>', '</opml>', '');
  return lines.join('\n');
}

export function renderImportReview(catalog) {
  const counts = {};
  for (const entry of catalog.imports) counts[entry.decision] = (counts[entry.decision] || 0) + 1;
  const lines = ['# Feedly import review', '', '<!-- Generated from feeds.json. -->', '', `Reviewed ${catalog.reviewedOn}: ${catalog.imports.length} original subscriptions; ${catalog.feeds.length} active feeds.`, '', Object.entries(counts).map(([key, count]) => `${key}: ${count}`).join('; ') + '.', '', 'Each original URL is accounted for below. Excluded means unsuitable for this verified feed bundle at review time; a temporary request failure does not establish that a publisher has closed. Dead or repurposed addresses are shown as text, not recommendations.', '', 'Multiple topic feeds from one publisher are intentional; subscribing to them can still produce overlapping articles. The importer deduplicates subscriptions, not individual stories.', ''];
  for (const entry of catalog.imports) {
    const target = catalog.feeds.find(feed => feed.id === entry.feedId);
    lines.push(`## ${markdown(entry.name)}`, '', `Original: \`${entry.url}\``, '', `Decision: **${entry.decision}**${target ? ` → ${target.name} (\`${target.feed}\`)` : ''}. ${entry.reason}`, '');
  }
  return lines.join('\n');
}
